### ISSUE TITLE
Fridump: 

### ISSUE THREAD

**Issue by poldenais** [Nightbringer21/fridump#17]
Hi All,
I got fridump to run before but now I'm getting the error **No module named frida**.
When i connect the Jailbroken iPad up to the test machine, I can run frida-ps -U successfully. It lists out all the processes on the iPAD.

When i then goto run python fridump.py -U -s -r AppName, I get the error below.

```
python fridump.py -U -s -r AppName
Traceback (most recent call last):
  File "fridump.py", line 2, in <module>
    import frida
ImportError: No module named frida
```

The iPad iOS version is : 11.3.1

**Comment by Night-test** [comment]
The error appears to be related to your frida installation rather than fridump.

Depending on your installation, you might have installed the frida module only on Python2 and not 3 or vice versa.

Try running the following commands:

pip install frida
pip install frida -- upgrade

pip3 install frida
pip3 install frida -- upgrade

**Comment by Night-test** [comment]
Let me know if it works and if not, I will try to investigate the issue further.

**Comment by poldenais** [comment]
> Let me know if it works and if not, I will try to investigate the issue further.

Hi Sorry, I got it working then. I had to add sudo in front this time whatever I changed.

sudo -H python fridump.py -U -s -r APPNAME
