### ISSUE TITLE
Can't connect to APP. Have you connected the device?

### ISSUE THREAD

**Issue by chackokavanattu12** [Nightbringer21/fridump#9]
Hi I have a issue while testing my android device after giving all the parameters its showing "Can't connect to App. Have you connected the device?" I know i have the device connected i am able to adb shell into the device? 

Kindly let me know what the issue would be.

![image](https://user-images.githubusercontent.com/6950547/31984581-b7045e28-b97f-11e7-9ed7-9a46bc8c290e.png)

**Comment by Nightbringer21** [comment]
Hi,

The reason you are getting this issue is because you are trying to attach to an application named "4794", which I believe that is actually the process id. Fridump needs the package name as argument to work.

Please see here for more examples on how to use it for Android applications:
http://pentestcorner.com/fridump-android-examples/
